version: '3'

services:

  db:
    container_name: ${DB_CONTAINER_NAME}
    build: ./db
    ports:
      - ${DB_HOST_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/files:/files

  php:
    container_name: ${PHP_CONTAINER_NAME}
    build: ./php
    ports:
      - ${PHP_FPM_HOST_PORT}:9000
    volumes:
      - ${PHP_HOST_WWW_PATH}:/var/www
      - ${PHP_HOST_COMPOSER_DATA_PATH}:/root/.composer
    working_dir: /var/www
    depends_on:
      - db

  nginx:
    container_name: ${NGINX_CONTAINER_NAME}
    build: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ${NGINX_HOST_WWW_PATH}:/var/www
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
    depends_on:
      - php

